config/routes.rb
Rails.application.routes.draw do
  get 'gdgfayoum/index'

  resources :members
  root "members#index"

end

app/models/member.rb
class Member < ActiveRecord::Base
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gdgfayoum_controller.rb
class GdgfayoumController < ApplicationController
  def index
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :permalink, :age, :retired, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gdgfayoum_helper.rb
module GdgfayoumHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/gdgfayoum/index.html.erb
<h1>Gdgfayoum#index</h1>
<p>Welcome</p>

app/views/members/_form.html.erb
<%= form_for @member, :html => { :class => "form-horizontal member" } do |f| %>

    <% if @member.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @member.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@member[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :permalink, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :permalink, :class => 'form-control' %>
    </div>
    <%= error_span(@member[:permalink]) %>
  </div>
  <div class="control-group">
    <%= f.label :age, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :age, :class => 'form-control' %>
    </div>
    <%= error_span(@member[:age]) %>
  </div>
  <div class="control-group">
    <%= f.label :retired, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :retired, :class => 'form-control' %>
    </div>
    <%= error_span(@member[:retired]) %>
  </div>
  <div class="control-group">
    <%= f.label :avatar_file_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :avatar %>
    </div>
    <%= error_span(@member[:avatar_file_name]) %>
  </div>
  </br>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            members_path, :class => 'btn btn-default' %>

<% end %>

app/views/members/edit.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/members/index.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:permalink) %></th>
      <th><%= model_class.human_attribute_name(:age) %></th>
      <th><%= model_class.human_attribute_name(:retired) %></th>
      <th><%= model_class.human_attribute_name(:avatar_file_name) %></th>
      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.id, member_path(member) %></td>
        <td><%= member.name %></td>
        <td><%= member.permalink %></td>
        <td><%= member.age %></td>
        <td><%= member.retired %></td>
        <td><%= image_tag member.avatar.url(:thumb) %></td>
        
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_member_path(member), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      member_path(member),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_member_path,
            :class => 'btn btn-primary' %>

app/views/members/new.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/members/show.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @member.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:permalink) %>:</strong></dt>
  <dd><%= @member.permalink %></dd>
  <dt><strong><%= model_class.human_attribute_name(:age) %>:</strong></dt>
  <dd><%= @member.age %></dd>
  <dt><strong><%= model_class.human_attribute_name(:retired) %>:</strong></dt>
  <dd><%= @member.retired %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_file_name) %>:</strong></dt>
  <dd><%= @member.avatar_file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_content_type) %>:</strong></dt>
  <dd><%= @member.avatar_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_file_size) %>:</strong></dt>
  <dd><%= @member.avatar_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_updated_at) %>:</strong></dt>
  <dd><%= @member.avatar_updated_at %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              members_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_member_path(@member), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              member_path(@member),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>